Repository aimhubio/aim, pull requests merged in 2020-07, with the labels that each got.

#164 Feature/readme docs restructure
  README.md
  docs/README.md
  docs/contributor-guide.md
Labels: Status: Review needed, documentation

#170 add panel sneak peek
  README.md
Labels: Status: In progress, documentation

#162 Tensorflow 2.x checkpoint integration with callbacks
  aim/artifacts/model.py
  aim/artifacts/utils.py
  aim/engine/utils.py
  examples/.gitignore
  examples/__init__.py
  examples/model_tracking_examples/keras_vgg_save.py
  examples/model_tracking_examples/pytorch_model_load.py
  examples/model_tracking_examples/pytorch_model_save.py
  examples/model_tracking_examples/tf2_model_load.py
  examples/model_tracking_examples/tf2_model_save.py
  examples/model_tracking_examples/tf_estimator_load.py
  examples/model_tracking_examples/tf_estimator_save.py
  examples/model_tracking_examples/tf_model_load.py
  examples/model_tracking_examples/tf_model_save.py
  examples/pytorch_track_all.py
  examples/tf_model_load.py
Labels: Status: Review needed, Type: Enhancement

#178 Add Tensorboard integration docs
  README.md
Labels: review needed
