Repository aimhubio/aim, pull requests merged in 2021-09, with the labels that each got.

#650 Add ability to save page url in local storage
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx
  aim/web/ui_v2/src/services/api/api.ts
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/utils/storage.ts
Labels: approved

#651 Implement content loader and no data placeholder for bookmarks page
  aim/web/ui_v2/src/components/BusyLoaderWrapper/BusyLoaderWrapper.tsx
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Bookmarks/Bookmarks.tsx
  aim/web/ui_v2/src/pages/Bookmarks/BookmarksContainer.tsx
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui_v2/src/services/models/bookmarks/bookmarksAppModel.ts
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/types/pages/bookmarks/Bookmarks.d.ts
  aim/web/ui_v2/src/types/services/models/bookmarks/bookmarksAppModel.d.ts
Labels: review needed

#649 Add Charts styles
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.scss
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui_v2/src/components/ChartPanel/PopoverContent/PopoverContent.tsx
  aim/web/ui_v2/src/components/HighPlot/HighPlot.tsx
  aim/web/ui_v2/src/components/LineChart/LineChart.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/components/ChartPanel/ChartPanel.d.ts
  aim/web/ui_v2/src/types/components/HighPlot/HighPlot.d.ts
  aim/web/ui_v2/src/types/components/LineChart/LineChart.d.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawArea.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawAxes.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawHoverAttributes.d.ts
  aim/web/ui_v2/src/utils/d3/drawArea.ts
  aim/web/ui_v2/src/utils/d3/drawAxes.ts
  aim/web/ui_v2/src/utils/d3/drawHoverAttributes.ts
  aim/web/ui_v2/src/utils/d3/drawParallelAxes.ts
  aim/web/ui_v2/src/utils/d3/drawParrallelArea.ts
Labels: in progress, approved

#653 Confirmation popover styling
  aim/web/ui_v2/src/components/ConfirmModal/ConfirmModal.scss
  aim/web/ui_v2/src/components/ConfirmModal/ConfirmModal.tsx
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
  aim/web/ui_v2/src/pages/Tags/TagDelete.tsx
  aim/web/ui_v2/src/pages/Tags/TagSoftDelete.tsx
  aim/web/ui_v2/src/pages/Tags/TagsList.tsx
  aim/web/ui_v2/src/styles/_global.scss
  aim/web/ui_v2/src/styles/_utils.scss
  aim/web/ui_v2/src/styles/abstracts/_variables.scss
  aim/web/ui_v2/src/types/components/ConfirmModal/ConfirmModal.d.ts
  aim/web/ui_v2/src/types/pages/tags/Tags.d.ts
Labels: review needed

#654 Add LineChart margins
  aim/web/ui_v2/src/utils/d3/drawAxes.ts
  aim/web/ui_v2/src/utils/d3/processData.ts
Labels: review needed

#655 Run search pagination
  aim/sdk/repo.py
  aim/sdk/trace.py
  aim/storage/structured/db.py
  aim/storage/structured/sql_engine/entities.py
  aim/web/api/runs/utils.py
  aim/web/api/runs/views.py
  tests/api/test_run_api.py
Labels: review needed

#657 Add content loader in metrics page
  aim/web/ui_v2/src/components/BusyLoaderWrapper/BusyLoaderWrapper.tsx
  aim/web/ui_v2/src/components/ChartLoader/ChartLoader.scss
  aim/web/ui_v2/src/components/ChartLoader/ChartLoader.tsx
  aim/web/ui_v2/src/components/TableLoader/TableLoader.scss
  aim/web/ui_v2/src/components/TableLoader/TableLoader.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.scss
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/components/BusyLoaderWrapper/BusyLoaderWrapper.d.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
Labels: review needed

#658 Enhance Button comopnent
  aim/web/ui_v2/src/components/Button/Button.scss
  aim/web/ui_v2/src/components/Button/Button.tsx
  aim/web/ui_v2/src/components/Theme/Theme.tsx
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.tsx
  aim/web/ui_v2/src/styles/base/_reset.scss
  aim/web/ui_v2/src/types/components/Button/Button.d.ts
Labels: review needed

#660 fix bookmark card styles
  aim/web/ui_v2/src/components/Button/Button.tsx
  aim/web/ui_v2/src/components/ConfirmModal/ConfirmModal.tsx
  aim/web/ui_v2/src/components/Theme/Theme.tsx
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
Labels: review needed

#661 Fix home page styles
  aim/web/ui_v2/package.json
  aim/web/ui_v2/src/components/CopyToClipBoard/CopyToClipBoard.tsx
  aim/web/ui_v2/src/pages/Home/components/Activity/Activity.tsx
  aim/web/ui_v2/src/pages/Home/components/ExploreAimCard/ExploreAimCard.scss
Labels: approved

#663 Fix LineChart axes formatting issues
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui_v2/src/components/LineChart/LineChart.tsx
  aim/web/ui_v2/src/components/TooltipContentPopover/TooltipContentPopover.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/utils/d3/drawAxes.ts
Labels: review needed

#664 Clean up requirements
  aim/sdk/metric.py
  requirements.dev.txt
  requirements.txt
  setup.py
Labels: review needed

#665 Feature/add run single page layout styling
  aim/web/ui_v2/src/assets/icons/errorIcon.svg
  aim/web/ui_v2/src/assets/icons/successIcon.svg
  aim/web/ui_v2/src/components/AppBar/AppBar.scss
  aim/web/ui_v2/src/components/BusyLoaderWrapper/BusyLoaderWrapper.tsx
  aim/web/ui_v2/src/components/Button/Button.tsx
  aim/web/ui_v2/src/components/CodeBlock/CodeBlock.scss
  aim/web/ui_v2/src/components/EmptyComponent/EmptyComponent.scss
  aim/web/ui_v2/src/components/EmptyComponent/EmptyComponent.tsx
  aim/web/ui_v2/src/components/HeatMap/HeatMapStyle.scss
  aim/web/ui_v2/src/components/NotificationContainer/NotificationContainer.scss
  aim/web/ui_v2/src/components/NotificationContainer/NotificationContainer.tsx
  aim/web/ui_v2/src/components/SelectTag/SelectTag.scss
  aim/web/ui_v2/src/components/SideBar/Sidebar.scss
  aim/web/ui_v2/src/components/Table/ExpandIcon.tsx
  aim/web/ui_v2/src/components/Table/SortIndicator.tsx
  aim/web/ui_v2/src/components/Table/Table.scss
  aim/web/ui_v2/src/components/TagForm/TagForm.scss
  aim/web/ui_v2/src/components/TagLabel/TagLabel.scss
  aim/web/ui_v2/src/components/TagLabel/TagLabel.tsx
  aim/web/ui_v2/src/components/Theme/Theme.tsx
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui_v2/src/pages/Home/components/Activity/Activity.scss
  aim/web/ui_v2/src/pages/Home/components/ExploreAimCard/ExploreAimCard.scss
  aim/web/ui_v2/src/pages/Home/components/SetupGuide/SetupGuide.scss
  aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.scss
  aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.scss
  aim/web/ui_v2/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.scss
  aim/web/ui_v2/src/pages/Metrics/components/Table/SortPopover/SortPopover.scss
  aim/web/ui_v2/src/pages/RunDetail/RunDetail.scss
  aim/web/ui_v2/src/pages/RunDetail/RunDetail.tsx
  aim/web/ui_v2/src/pages/RunDetail/RunDetailMetricsAndSystemTab.tsx
  aim/web/ui_v2/src/pages/RunDetail/RunDetailParamsTab.tsx
  aim/web/ui_v2/src/pages/RunDetail/RunDetailSettingsTab.tsx
  aim/web/ui_v2/src/pages/RunDetail/RunMetricCard.tsx
  aim/web/ui_v2/src/pages/Tags/Tags.scss
  aim/web/ui_v2/src/pages/Tags/TagsTable.tsx
  aim/web/ui_v2/src/services/models/runs/runDetailAppModel.ts
  aim/web/ui_v2/src/services/models/tags/tagsAppModel.ts
  aim/web/ui_v2/src/styles/abstracts/_variables.scss
  aim/web/ui_v2/src/styles/base/_reset.scss
  aim/web/ui_v2/src/styles/components/_inputs.scss
  aim/web/ui_v2/src/types/components/AppBar/AppBar.d.ts
  aim/web/ui_v2/src/types/pages/runs/Runs.d.ts
  aim/web/ui_v2/src/utils/processDurationTime.ts
Labels: review needed

#666 Fix query stripping
  aim/storage/query.py
  aim/web/api/runs/pydantic_models.py
  aim/web/api/tags/pydantic_models.py
Labels: review needed

#669 Hide charts when resizing panel
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.scss
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui_v2/src/components/ChartPanel/config.ts
  aim/web/ui_v2/src/hooks/resize/usePanelResize.ts
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/types/components/ChartPanel/ChartPanel.d.ts
  aim/web/ui_v2/src/types/components/LineChart/LineChart.d.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/utils/d3/drawAxes.ts
  aim/web/ui_v2/src/utils/d3/drawHoverAttributes.ts
Labels: review needed

#662 Fix Tags page issues
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Tags/TagDetail.tsx
  aim/web/ui_v2/src/pages/Tags/Tags.scss
  aim/web/ui_v2/src/pages/Tags/TagsList.tsx
  aim/web/ui_v2/src/pages/Tags/TagsTable.tsx
  aim/web/ui_v2/src/services/models/tags/tagsAppModel.ts
  aim/web/ui_v2/src/types/components/Table/Table.d.ts
  aim/web/ui_v2/src/types/pages/tags/Tags.d.ts
Labels: review needed

#668 Add custom table with enhanced grouping layout
  aim/web/ui_v2/public/index.html
  aim/web/ui_v2/src/components/CustomTable/Table.scss
  aim/web/ui_v2/src/components/CustomTable/Table.tsx
  aim/web/ui_v2/src/components/CustomTable/TableCell.tsx
  aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx
  aim/web/ui_v2/src/components/CustomTable/TablePopover.tsx
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/index.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui_v2/src/pages/Metrics/components/TableColumns/TableColumns.tsx
  aim/web/ui_v2/src/pages/Tags/TagsTable.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/types/components/Table/Table.d.ts
  aim/web/ui_v2/src/types/pages/metrics/components/TableColumns/TableColumns.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
Labels: review needed

#670 Hide-LineChart-tooltip-on-zoom-mode
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Tags/TagsTable.tsx
  aim/web/ui_v2/src/types/components/ChartPanel/ChartPanel.d.ts
Labels: review needed

#672 Fix issue with showing metric name in alignment popover
  aim/web/ui_v2/src/components/AlignmentPopover/AlignmentPopover.tsx
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/hooks/resize/usePanelResize.ts
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui_v2/src/services/models/projects/projectsModel.ts
  aim/web/ui_v2/src/types/components/AlignmentPopover/AlignmentPopover.d.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/metrics/components/controls/Controls.d.ts
Labels: review needed

#674 Implement params state saving in url
  aim/web/ui_v2/src/components/HighPlot/HighPlot.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/pages/RunDetail/RunDetail.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawParallelHoverAttributes.d.ts
  aim/web/ui_v2/src/utils/d3/drawParallelAxes.ts
  aim/web/ui_v2/src/utils/d3/drawParallelHoverAttributes.ts
  aim/web/ui_v2/src/utils/d3/drawParallelLines.ts
  aim/web/ui_v2/src/utils/d3/lineGenerator.ts
Labels: review needed

#676 Implement Icons as fonts in project
  aim/web/ui_v2/src/assets/icons/copy.svg
  aim/web/ui_v2/src/assets/icons/delete.svg
  aim/web/ui_v2/src/assets/logo.svg
  aim/web/ui_v2/src/components/CodeBlock/CodeBlock.tsx
  aim/web/ui_v2/src/components/ConfirmModal/ConfirmModal.scss
  aim/web/ui_v2/src/components/CopyToClipBoard/CopyToClipBoard.tsx
  aim/web/ui_v2/src/components/CustomTable/Table.scss
  aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx
  aim/web/ui_v2/src/components/Icon/Icon.scss
  aim/web/ui_v2/src/components/Icon/Icon.tsx
  aim/web/ui_v2/src/components/SelectTag/SelectTag.tsx
  aim/web/ui_v2/src/components/SideBar/SideBar.tsx
  aim/web/ui_v2/src/components/SideBar/Sidebar.scss
  aim/web/ui_v2/src/components/Table/Table.scss
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/fonts/icomoon/fonts/icomoon.eot
  aim/web/ui_v2/src/fonts/icomoon/fonts/icomoon.svg
  aim/web/ui_v2/src/fonts/icomoon/fonts/icomoon.ttf
  aim/web/ui_v2/src/fonts/icomoon/fonts/icomoon.woff
  aim/web/ui_v2/src/fonts/icomoon/icomoonIcons.scss
  aim/web/ui_v2/src/fonts/icomoon/selection.json
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
  aim/web/ui_v2/src/pages/Home/components/ExploreAim/ExploreAim.tsx
  aim/web/ui_v2/src/pages/Home/components/ExploreAimCard/ExploreAimCard.scss
  aim/web/ui_v2/src/pages/Home/components/ExploreAimCard/ExploreAimCard.tsx
  aim/web/ui_v2/src/pages/Home/components/SetupGuide/SetupGuide.scss
  aim/web/ui_v2/src/pages/Home/components/SetupGuide/SetupGuide.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.scss
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui_v2/src/pages/Metrics/components/GroupingItem/GroupingItem.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx
  aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/components/Controls/Controls.tsx
  aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.tsx
  aim/web/ui_v2/src/pages/Tags/TagDelete.tsx
  aim/web/ui_v2/src/pages/Tags/TagDetail.tsx
  aim/web/ui_v2/src/pages/Tags/TagRunsTable.tsx
  aim/web/ui_v2/src/pages/Tags/TagSoftDelete.tsx
  aim/web/ui_v2/src/pages/Tags/Tags.scss
  aim/web/ui_v2/src/pages/Tags/TagsContainer.tsx
  aim/web/ui_v2/src/pages/Tags/TagsList.tsx
  aim/web/ui_v2/src/pages/Tags/TagsTable.tsx
  aim/web/ui_v2/src/routes/routes.tsx
  aim/web/ui_v2/src/styles/abstracts/_variables.scss
  aim/web/ui_v2/src/types/components/Icon/Icon.d.ts
Labels: review needed

#675 Minor fixes on storage and backend
  aim/storage/container.py
  aim/web/api/views.py
Labels: review needed

#679 Added table to Params page
  aim/web/ui_v2/src/components/HighPlot/HighPlot.scss
  aim/web/ui_v2/src/components/HighPlot/HighPlot.tsx
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Params/Params.scss
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/utils/d3/drawParallelHoverAttributes.d.ts
  aim/web/ui_v2/src/utils/d3/drawParallelHoverAttributes.ts
Labels: approved

#682 Implement export functionality in Params table
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/utils/getObjectPaths.ts
Labels: approved

#684 Runs explorer
  aim/web/ui_v2/src/components/HeatMap/HeatMap.tsx
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Runs/Runs.scss
  aim/web/ui_v2/src/pages/Runs/Runs.tsx
  aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx
  aim/web/ui_v2/src/pages/Runs/RunsTable.tsx
  aim/web/ui_v2/src/pages/Runs/components/RunsBar/RunsBar.tsx
  aim/web/ui_v2/src/pages/Runs/components/RunsTableColumns/RunsTableColumns.tsx
  aim/web/ui_v2/src/pages/Runs/components/SearchBar/SearchBar.scss
  aim/web/ui_v2/src/pages/Runs/components/SearchBar/SearchBar.tsx
  aim/web/ui_v2/src/pages/Tags/Tags.scss
  aim/web/ui_v2/src/services/api/runs/runsService.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
  aim/web/ui_v2/src/types/components/Table/Table.d.ts
  aim/web/ui_v2/src/types/pages/runs/Runs.d.ts
  aim/web/ui_v2/src/types/services/models/params/paramsAppModel.d.ts
Labels: approved

#686 Fix explore page css
  aim/web/ui_v2/src/pages/Runs/Runs.scss
  aim/web/ui_v2/src/services/api/runs/runsService.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
Labels: review needed

#689 Add zoom history actions on LineChart
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui_v2/src/components/HighPlot/HighPlot.tsx
  aim/web/ui_v2/src/components/LineChart/LineChart.tsx
  aim/web/ui_v2/src/components/ZoomInPopover/ZoomInPopover.tsx
  aim/web/ui_v2/src/components/ZoomOutPopover/ZoomOutPopover.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/RunDetail/RunMetricCard.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/types/components/ChartPanel/ChartPanel.d.ts
  aim/web/ui_v2/src/types/components/HighPlot/HighPlot.d.ts
  aim/web/ui_v2/src/types/components/HighlightModesPopover/HighlightModesPopover.d.ts
  aim/web/ui_v2/src/types/components/LineChart/LineChart.d.ts
  aim/web/ui_v2/src/types/components/TooltipContentPopover/TooltipContentPopover.d.ts
  aim/web/ui_v2/src/types/components/ZoomInPopover/ZoomInPopover.d.ts
  aim/web/ui_v2/src/types/components/ZoomOutPopover/ZoomOutPopover.d.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/metrics/components/controls/Controls.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawArea.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawAxes.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawBrush.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawParallelAxesBrush.d.ts
  aim/web/ui_v2/src/utils/d3/drawArea.ts
  aim/web/ui_v2/src/utils/d3/drawAxes.ts
  aim/web/ui_v2/src/utils/d3/drawBrush.ts
  aim/web/ui_v2/src/utils/d3/drawLines.ts
  aim/web/ui_v2/src/utils/d3/drawParrallelArea.ts
Labels: review needed

#681 Fix the issue when trying to query or collect params on an empty repo
  aim/sdk/repo.py
  aim/storage/union.py
Labels: review needed

#693 Improve aggregated method in line chart
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/components/LineChart/LineChart.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricModel.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
  aim/web/ui_v2/src/types/utils/d3/processData.d.ts
  aim/web/ui_v2/src/utils/d3/drawHoverAttributes.ts
  aim/web/ui_v2/src/utils/d3/drawLines.ts
Labels: approved

#696 Finalize runs explore page
  aim/web/ui_v2/src/components/Button/Button.scss
  aim/web/ui_v2/src/components/HeatMap/HeatMap.tsx
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Runs/Runs.tsx
  aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx
  aim/web/ui_v2/src/pages/Runs/RunsTable.tsx
  aim/web/ui_v2/src/pages/Runs/components/RunsBar/RunsBar.tsx
  aim/web/ui_v2/src/pages/Runs/components/SearchBar/SearchBar.scss
  aim/web/ui_v2/src/pages/Runs/components/SearchBar/SearchBar.tsx
  aim/web/ui_v2/src/services/api/runs/runsService.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
  aim/web/ui_v2/src/types/components/Table/Table.d.ts
  aim/web/ui_v2/src/types/pages/metrics/components/Controls/Controls.d.ts
  aim/web/ui_v2/src/types/pages/runs/Runs.d.ts
Labels: review needed

#704 Fix the case when empty query returns syntax error
  aim/storage/query.py
Labels: review needed

#705 Add missing styles and functional to params page
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
  aim/web/ui_v2/src/types/pages/metrics/components/TableColumns/TableColumns.d.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
  aim/web/ui_v2/src/types/services/models/params/paramsAppModel.d.ts
  aim/web/ui_v2/src/types/utils/d3/drawParallelHoverAttributes.d.ts
  aim/web/ui_v2/src/utils/d3/drawParallelHoverAttributes.ts
  aim/web/ui_v2/src/utils/getObjectPaths.ts
Labels: review needed

#703 Add runs table actions
  aim/web/ui_v2/src/components/HeatMap/HeatMap.tsx
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Runs/Runs.tsx
  aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx
  aim/web/ui_v2/src/pages/Runs/RunsTable.tsx
  aim/web/ui_v2/src/pages/Runs/components/RunsTableColumns/RunsTableColumns.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
  aim/web/ui_v2/src/types/components/Table/Table.d.ts
  aim/web/ui_v2/src/types/pages/runs/Runs.d.ts
  aim/web/ui_v2/src/types/services/models/params/paramsAppModel.d.ts
Labels: review needed

#708 Fix hiddenColumns props on runs table
  aim/web/ui_v2/src/pages/Runs/RunsTable.tsx
Labels: review needed

#707 Add Params page label delete functionality
  aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.tsx
Labels: review needed

#710 Fix grouping subtitles
  aim/web/ui_v2/src/components/GroupingPopover/GroupingPopover.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Grouping/Grouping.tsx
  aim/web/ui_v2/src/pages/Metrics/components/GroupingItem/GroupingItem.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.scss
  aim/web/ui_v2/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.scss
  aim/web/ui_v2/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
  aim/web/ui_v2/src/types/services/models/params/paramsAppModel.d.ts
Labels: approved

#711 Fixed select form layout issues
  aim/web/ui_v2/src/components/ControlPopover/ControlPopover.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.scss
  aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.scss
  aim/web/ui_v2/src/types/components/ControlPopover/ControlPopover.d.ts
  aim/web/ui_v2/src/utils/d3/drawHoverAttributes.ts
  aim/web/ui_v2/src/utils/formatXAxisValueByAlignment.ts
Labels: review needed

#713 Display toaster on bookmarks create update
  aim/web/ui_v2/src/components/NotificationContainer/NotificationContainer.scss
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/routes/routes.tsx
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
Labels: approved

#715 tune single run page
  aim/web/ui_v2/src/pages/RunDetail/RunDetail.tsx
  aim/web/ui_v2/src/pages/RunDetail/RunDetailParamsTab.tsx
Labels: review needed

#712 Fix Chart Popover disable enforce focus
  aim/web/ui_v2/src/components/ChartPanel/ChartPopover/ChartPopover.tsx
Labels: approved

#716 Improve empty data component illustration format to svg
  aim/web/ui_v2/src/assets/icons/noData.png
  aim/web/ui_v2/src/assets/icons/noData.svg
  aim/web/ui_v2/src/components/EmptyComponent/EmptyComponent.tsx
Labels: review needed

#714 Fix run finalization
  aim/storage/container.py
Labels: review needed

#717 Implement table resize state change functionality
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.scss
  aim/web/ui_v2/src/components/ResizeModeActions/ResizeModeActions.scss
  aim/web/ui_v2/src/components/ResizeModeActions/ResizeModeActions.tsx
  aim/web/ui_v2/src/components/ResizePanel/ResizePanel.scss
  aim/web/ui_v2/src/components/ResizePanel/ResizePanel.tsx
  aim/web/ui_v2/src/components/Table/Table.scss
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/components/Theme/Theme.tsx
  aim/web/ui_v2/src/config/enums/tableEnums.ts
  aim/web/ui_v2/src/hooks/resize/usePanelResize.ts
  aim/web/ui_v2/src/pages/Metrics/Metrics.scss
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Params/Params.scss
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/components/Icon/Icon.d.ts
  aim/web/ui_v2/src/types/components/ResizeModeActions/ResizeModeActions.d.ts
  aim/web/ui_v2/src/types/components/ResizePanel/ResizePanel.d.ts
  aim/web/ui_v2/src/types/components/Table/Table.d.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
Labels: review needed

#720 Implement table config saving in local storage
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
Labels: review needed

#722 Fix panel resizing state bug
  aim/web/ui_v2/src/hooks/resize/usePanelResize.ts
  aim/web/ui_v2/src/pages/Metrics/Metrics.scss
  aim/web/ui_v2/src/pages/Params/Params.scss
Labels: review needed

#723 Add tooltips for chart control buttons
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui_v2/src/pages/Params/components/Controls/Controls.tsx
Labels: review needed

#725 Exception handler
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/services/api/api.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
Labels: review needed

#726 Update table grouping action popover
  aim/web/ui_v2/src/components/ControlPopover/ControlPopover.tsx
  aim/web/ui_v2/src/components/CustomTable/Table.scss
  aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx
  aim/web/ui_v2/src/types/components/ControlPopover/ControlPopover.d.ts
Labels: review needed

#724 Fix Table export CSV button for all (Metrics, Params, Runs) pages
  aim/web/ui_v2/src/components/CustomTable/Table.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.tsx
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/pages/Runs/components/RunsTableColumns/RunsTableColumns.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
  aim/web/ui_v2/src/types/services/models/params/paramsAppModel.d.ts
Labels: review needed

#728 Tune chart popover visibility on active focused point
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
Labels: review needed

#731 Implement metrics columns in table
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/pages/Runs/components/RunsTableColumns/RunsTableColumns.tsx
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
Labels: review needed

#732 Add loader component as an infinite loader on runs page
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Runs/Runs.scss
  aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx
  aim/web/ui_v2/src/pages/Runs/RunsTable.tsx
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
Labels: approved

#737 Improve params keys flattening helper
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/utils/getObjectPaths.ts
Labels: review needed

#738 Fix handling bug of api error corner cases
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
Labels: approved

#740 Implement hover and focus states of tag color radios
  aim/web/ui_v2/src/components/TagForm/TagForm.scss
  aim/web/ui_v2/src/components/TagForm/TagForm.tsx
  aim/web/ui_v2/src/services/models/model.ts
Labels: review needed

#736 Fix table export with custom row renderer
  aim/web/ui_v2/src/components/ChartPanel/config.ts
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
Labels: approved

#741 Implement row visibility toggle icon in actions column
  aim/web/ui_v2/src/components/CustomTable/Table.scss
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
Labels: review needed

#742 Add row height change functionality on table
  aim/web/ui_v2/src/components/CustomTable/Table.scss
  aim/web/ui_v2/src/components/CustomTable/Table.tsx
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/config/table/tableConfigs.ts
  aim/web/ui_v2/src/pages/Metrics/components/Table/RowHeightPopover/RowHeightPopover.tsx
Labels: review needed

#743 Keep table resize state in model config
  aim/web/ui_v2/src/hooks/resize/usePanelResize.ts
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
Labels: approved

#744 Fix visited state color of "get involved" cards links
  aim/web/ui_v2/src/pages/Home/components/ExploreAim/ExploreAim.scss
Labels: approved

#746 HighPlot tune dimensions ticks and titles
  aim/web/ui_v2/src/components/HighPlot/HighPlot.scss
  aim/web/ui_v2/src/components/HighPlot/HighPlot.tsx
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/utils/d3/drawParallelAxes.d.ts
  aim/web/ui_v2/src/utils/d3/drawParallelAxes.ts
  aim/web/ui_v2/src/utils/getInnerTextFromHtml.ts
Labels: approved

#747 Update rendering dependencies in Table component
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
Labels: review needed

#749 Tune TagLabel component
  aim/web/ui_v2/src/components/TagLabel/TagLabel.scss
  aim/web/ui_v2/src/components/TagLabel/TagLabel.tsx
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.scss
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.scss
  aim/web/ui_v2/src/pages/Runs/components/RunsTableGrid/RunsTableGrid.tsx
  aim/web/ui_v2/src/types/components/SelectTag/SelectTag.d.ts
Labels: review needed

#750 Improve aggregation values column layout for area None mode
  aim/web/ui_v2/src/components/CustomTable/Table.scss
  aim/web/ui_v2/src/config/table/tableConfigs.ts
  aim/web/ui_v2/src/pages/Metrics/Metrics.scss
Labels: review needed

#755 Improve table css variables
  aim/web/ui_v2/public/favicon.ico
  aim/web/ui_v2/public/favicon.png
  aim/web/ui_v2/public/index.html
  aim/web/ui_v2/public/logo.png
  aim/web/ui_v2/public/manifest.json
  aim/web/ui_v2/src/assets/logo.svg
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.scss
  aim/web/ui_v2/src/components/CustomTable/Table.scss
  aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx
  aim/web/ui_v2/src/components/ResizePanel/ResizePanel.scss
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/styles/abstracts/_functions.scss
  aim/web/ui_v2/src/styles/abstracts/_variables.scss
  aim/web/ui_v2/src/types/pages/bookmarks/Bookmarks.d.ts
Labels: review needed

#759 Improve bookmarks page redirection to metrics page
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Metrics/components/BookmarkForm/BookmarkForm.tsx
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
Labels: review needed

#753 Integrate ga segment to collect telemetry data
  aim/web/ui_v2/public/index.html
  aim/web/ui_v2/src/components/HeatMap/HeatMap.tsx
  aim/web/ui_v2/src/components/ZoomInPopover/ZoomInPopover.tsx
  aim/web/ui_v2/src/config/alignment/alignmentOptions.ts
  aim/web/ui_v2/src/config/enums/tableEnums.ts
  aim/web/ui_v2/src/pages/Bookmarks/BookmarksContainer.tsx
  aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/pages/RunDetail/RunDetail.tsx
  aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx
  aim/web/ui_v2/src/pages/Tags/Tags.tsx
  aim/web/ui_v2/src/pages/Tags/TagsContainer.tsx
  aim/web/ui_v2/src/pages/Tags/TagsList.tsx
  aim/web/ui_v2/src/services/analytics.ts
  aim/web/ui_v2/src/services/models/bookmarks/bookmarksAppModel.ts
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runDetailAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
  aim/web/ui_v2/src/services/models/tags/tagsAppModel.ts
  aim/web/ui_v2/src/utils/aggregateGroupData.ts
Labels: review needed

#761 Fix chart/svg drawing issue for Safari
  aim/web/ui_v2/src/fonts/icomoon/fonts/icomoon.eot
  aim/web/ui_v2/src/fonts/icomoon/fonts/icomoon.svg
  aim/web/ui_v2/src/fonts/icomoon/fonts/icomoon.ttf
  aim/web/ui_v2/src/fonts/icomoon/fonts/icomoon.woff
  aim/web/ui_v2/src/fonts/icomoon/icomoonIcons.scss
  aim/web/ui_v2/src/fonts/icomoon/selection.json
  aim/web/ui_v2/src/pages/Metrics/Metrics.scss
  aim/web/ui_v2/src/pages/Params/Params.scss
  aim/web/ui_v2/src/utils/d3/drawArea.ts
Labels: review needed

#760 Add Table column's sort functionality
  aim/web/ui_v2/src/components/CustomTable/Table.tsx
  aim/web/ui_v2/src/components/Table/Table.scss
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/components/Table/TableSortIcons.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Table/SortPopover/SortPopover.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/types/components/Table/Table.d.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/metrics/components/SortPopover/SortPopover.d.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
Labels: review needed

#762 Improve chart tooltip table overlapping
  aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui_v2/src/components/ChartPanel/ChartPopover/ChartPopover.tsx
  aim/web/ui_v2/src/components/ChartPanel/PopoverContent/PopoverContent.tsx
  aim/web/ui_v2/src/types/components/ChartPanel/ChartPopover.d.ts
  aim/web/ui_v2/src/types/components/ChartPanel/PopoverContent.d.ts
Labels: review needed

#763 Add ability to attach run tags in chart tooltip
  aim/web/ui_v2/src/components/AttachedTagsList/AttachedTagsList.scss
  aim/web/ui_v2/src/components/AttachedTagsList/AttachedTagsList.tsx
  aim/web/ui_v2/src/components/ChartPanel/ChartPopover/ChartPopover.tsx
  aim/web/ui_v2/src/components/ChartPanel/PopoverContent/PopoverContent.scss
  aim/web/ui_v2/src/components/ChartPanel/PopoverContent/PopoverContent.tsx
  aim/web/ui_v2/src/components/ControlPopover/ControlPopover.tsx
  aim/web/ui_v2/src/components/SelectTag/SelectTag.scss
  aim/web/ui_v2/src/components/SelectTag/SelectTag.tsx
  aim/web/ui_v2/src/components/TagLabel/TagLabel.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui_v2/src/services/api/runs/runsService.ts
  aim/web/ui_v2/src/types/components/AttachedTagsList/AttachedTagsList.d.ts
  aim/web/ui_v2/src/types/components/ControlPopover/ControlPopover.d.ts
  aim/web/ui_v2/src/types/components/SelectTag/SelectTag.d.ts
  aim/web/ui_v2/src/types/components/TagLabel/TagLabel.d.ts
Labels: approved

#765 Tune table icon buttons
  aim/web/ui_v2/src/components/CustomTable/Table.scss
  aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx
  aim/web/ui_v2/src/components/ResizePanel/ResizePanel.scss
  aim/web/ui_v2/src/components/SideBar/Sidebar.scss
  aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.scss
  aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx
  aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
Labels: review needed

#766 Implement store column resized width value
  aim/web/ui_v2/src/components/Table/Table.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Params/Params.tsx
  aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx
  aim/web/ui_v2/src/pages/Runs/Runs.tsx
  aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx
  aim/web/ui_v2/src/pages/Runs/RunsTable.tsx
  aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
  aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/params/Params.d.ts
  aim/web/ui_v2/src/types/pages/runs/Runs.d.ts
  aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
Labels: review needed

#770 Fix Ignore outliers functionality
  aim/web/ui/src/pages/Metrics/Metrics.tsx
  aim/web/ui/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui/src/types/pages/metrics/components/controls/Controls.d.ts
  aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts
  aim/web/ui/src/utils/d3/processData.ts
Labels: review needed

#771 Improve active point resetting by clicking on table row
  aim/web/ui/src/components/HighPlot/HighPlot.tsx
  aim/web/ui/src/components/LineChart/LineChart.tsx
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
  aim/web/ui/src/types/components/LineChart/LineChart.d.ts
  aim/web/ui/src/types/utils/d3/drawParallelHoverAttributes.d.ts
  aim/web/ui/src/utils/d3/drawHoverAttributes.ts
  aim/web/ui/src/utils/d3/drawParallelHoverAttributes.ts
Labels: review needed

#777 Fix chart tooltip positioning
  aim/web/ui/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui/src/components/ChartPanel/ChartPopover/ChartPopover.tsx
  aim/web/ui/src/types/components/ChartPanel/PopoverContent.d.ts
  aim/web/ui/src/utils/getPositionBasedOnOverflow.ts
Labels: review needed

#773 Add requestAnimation frame on chart mouse move
  aim/web/ui/src/components/HighPlot/HighPlot.tsx
  aim/web/ui/src/components/LineChart/LineChart.tsx
  aim/web/ui/src/hooks/resize/usePanelResize.ts
  aim/web/ui/src/hooks/window/useResizeObserver.ts
  aim/web/ui/src/utils/d3/drawHoverAttributes.ts
  aim/web/ui/src/utils/d3/drawParallelHoverAttributes.ts
Labels: review needed

#775 Sub app division for apis and static files
  aim/web/api/__init__.py
  aim/web/api/views.py
Labels: review needed

#779 Add gzipper to compress static files
  aim/web/ui/package-lock.json
  aim/web/ui/package.json
Labels: review needed

#780 Integrate bundle analyzer
  aim/web/ui/package-lock.json
  aim/web/ui/package.json
  aim/web/ui/tasks/bundle-analyzer.js
Labels: review needed

#778 Improve URL sync with the app state
  aim/web/ui/src/components/CustomTable/Table.scss
  aim/web/ui/src/components/CustomTable/TableColumn.tsx
  aim/web/ui/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui/src/pages/Params/ParamsContainer.tsx
  aim/web/ui/src/pages/Runs/RunsContainer.tsx
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
  aim/web/ui/src/services/models/runs/runsAppModel.ts
  aim/web/ui/src/utils/getUrlWithParam.ts
Labels: review needed

#789 Fix params app state issue while routing from bookmarks
  aim/web/ui/src/components/CustomTable/TableColumn.tsx
  aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
  aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui/src/pages/Params/Params.tsx
  aim/web/ui/src/pages/Params/ParamsContainer.tsx
  aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui/src/pages/Runs/Runs.tsx
  aim/web/ui/src/pages/Runs/RunsContainer.tsx
Labels: review needed

#785 Fix HighPlot title ‘XSS’ injection issue
  aim/web/ui/src/components/HighPlot/HighPlot.scss
  aim/web/ui/src/services/models/params/paramsAppModel.ts
  aim/web/ui/src/utils/d3/drawParallelAxes.ts
  aim/web/ui/src/utils/getInnerTextFromHtml.ts
Labels: approved

#787 Docs restructure and improvement for v3
  .gitignore
  aim/__about__.py
  docs/OVERVIEW.md
  docs/source/_static/images/logo.svg
  docs/source/aim.rst
  docs/source/aim_sdk.rst
  docs/source/aim_storage.rst
  docs/source/api_references.rst
  docs/source/cli_references.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/integration_guides.rst
  docs/source/md/cli_references.md
  docs/source/md/guides/integrations/basic_aim_huggingface.md
  docs/source/md/guides/ql/basic_example.md
  docs/source/md/guides/tutorials/tutorial_1.md
  docs/source/md/guides/ui/basic_example.md
  docs/source/md/overview.md
  docs/source/md/quick-start/3_steps.md
  docs/source/md/quick-start/basic_query.md
  docs/source/md/quick-start/first_run.md
  docs/source/md/quick-start/integrations.md
  docs/source/md/quick-start/why_aim.md
  docs/source/modules.rst
  docs/source/overview.rst
  docs/source/ql_guides.rst
  docs/source/reference.rst
  docs/source/ui_guides.rst
  requirements.dev.txt
  requirements.docs.txt
Labels: docs

#791 Implement value formatting method for table
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
  aim/web/ui/src/services/models/runs/runsAppModel.ts
  aim/web/ui/src/utils/formatValue.ts
Labels: approved

#794 Disable row updating on hidden table
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
Labels: approved

#782 Remote fs support with sshfs
  aim/ext/sshfs/__init__.py
  aim/ext/sshfs/utils.py
  aim/sdk/repo.py
Labels: review needed

#793 Tune SelectForm input
  aim/web/ui/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx
  aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.scss
  aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx
  aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.scss
  aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.tsx
  aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.scss
  aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.tsx
Labels: review needed

#802 Improve params popovers selection part UX
  aim/web/ui/src/components/GroupingPopover/GroupingPopover.tsx
  aim/web/ui/src/components/TooltipContentPopover/TooltipContentPopover.tsx
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
Labels: review needed

#805 Fix bug in chart tooltip positioning
  aim/web/ui/src/components/ChartPanel/ChartPanel.tsx
  aim/web/ui/src/components/ChartPanel/ChartPopover/ChartPopover.scss
  aim/web/ui/src/components/ChartPanel/ChartPopover/ChartPopover.tsx
  aim/web/ui/src/components/ChartPanel/PopoverContent/PopoverContent.scss
  aim/web/ui/src/components/ChartPanel/PopoverContent/PopoverContent.tsx
  aim/web/ui/src/types/components/ChartPanel/ChartPopover.d.ts
  aim/web/ui/src/types/components/ChartPanel/PopoverContent.d.ts
  aim/web/ui/src/utils/getPositionBasedOnOverflow.ts
Labels: approved

#804 Fix UI layout shift to top on opening browser devtools from bottom
  aim/web/ui/src/App.scss
  aim/web/ui/src/App.tsx
  aim/web/ui/src/components/CustomTable/Table.scss
  aim/web/ui/src/components/SideBar/SideBar.tsx
  aim/web/ui/src/components/SideBar/Sidebar.scss
  aim/web/ui/src/components/Theme/Theme.tsx
  aim/web/ui/src/pages/Metrics/Metrics.scss
  aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.scss
  aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx
  aim/web/ui/src/pages/Params/Params.scss
  aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.scss
  aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.tsx
  aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.scss
  aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.tsx
  aim/web/ui/src/styles/components/_inputs.scss
Labels: review needed

#812 Update resize panel styles
  aim/web/ui/src/components/ChartLoader/ChartLoader.scss
  aim/web/ui/src/components/ChartLoader/ChartLoader.tsx
  aim/web/ui/src/components/ResizePanel/ResizePanel.scss
  aim/web/ui/src/components/ResizePanel/ResizePanel.tsx
  aim/web/ui/src/pages/Metrics/Metrics.tsx
  aim/web/ui/src/pages/Metrics/components/Controls/Controls.scss
  aim/web/ui/src/pages/Params/Params.tsx
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
  aim/web/ui/src/styles/abstracts/_variables.scss
  aim/web/ui/src/types/components/ChartLoader/ChartLoader.d.ts
  aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts
Labels: approved

#811 Tune styling of explorers
  aim/web/ui/src/App.scss
  aim/web/ui/src/components/AppBar/AppBar.scss
  aim/web/ui/src/components/CustomTable/Table.scss
  aim/web/ui/src/components/SideBar/Sidebar.scss
  aim/web/ui/src/components/Table/Table.scss
  aim/web/ui/src/components/Table/Table.tsx
  aim/web/ui/src/config/colors/colors.ts
  aim/web/ui/src/pages/Bookmarks/Bookmarks.tsx
  aim/web/ui/src/pages/Metrics/Metrics.scss
  aim/web/ui/src/pages/Metrics/Metrics.tsx
  aim/web/ui/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui/src/pages/Metrics/components/GroupingItem/groupingItemStyle.scss
  aim/web/ui/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx
  aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.scss
  aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx
  aim/web/ui/src/pages/Params/Params.scss
  aim/web/ui/src/pages/Params/Params.tsx
  aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.scss
  aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.tsx
  aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.tsx
  aim/web/ui/src/styles/abstracts/_variables.scss
  aim/web/ui/src/types/pages/metrics/components/MetricsBar/MetricsBar.d.ts
Labels: review needed

#815 Fix reset config functionality
  aim/web/ui/src/fonts/icomoon/fonts/icomoon.eot
  aim/web/ui/src/fonts/icomoon/fonts/icomoon.svg
  aim/web/ui/src/fonts/icomoon/fonts/icomoon.ttf
  aim/web/ui/src/fonts/icomoon/fonts/icomoon.woff
  aim/web/ui/src/fonts/icomoon/icomoonIcons.scss
  aim/web/ui/src/fonts/icomoon/selection.json
  aim/web/ui/src/pages/RunDetail/RunDetail.scss
  aim/web/ui/src/pages/Runs/Runs.scss
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
Labels: review needed
