Repository aimhubio/aim, pull requests merged in 2021-06, with the labels that each got.

#478 Add X axis custom alignment support
  CHANGELOG.md
  aim/engine/repo/metric.py
  aim/engine/repo/run.py
  aim/engine/repo/trace.py
  aim/web/app/commits/utils.py
  aim/web/app/commits/views.py
  aim/web/ui/package.json
  aim/web/ui/src/actions/hub/commit.js
  aim/web/ui/src/screens/hub/HubMainScreen/HubMainScreen.js
  aim/web/ui/src/screens/hub/HubMainScreen/HubMainScreen.less
  aim/web/ui/src/screens/hub/HubMainScreen/components/AlignmentWarning/AlignmentWarning.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/AlignmentWarning/AlignmentWarning.less
  aim/web/ui/src/screens/hub/HubMainScreen/components/ContextBox/ContextBox.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/ControlsSidebar/ControlsSidebar.less
  aim/web/ui/src/screens/hub/HubMainScreen/components/ControlsSidebar/components/ControlsSidebarAxesProperties/ControlsSidebarAxesProperties.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/Panel/Panel.less
  aim/web/ui/src/screens/hub/HubMainScreen/components/Panel/components/PanelChart/PanelChart.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/Panel/components/PanelChart/PanelChart.less
  aim/web/ui/src/screens/hub/HubMainScreen/components/Panel/components/PopUp/PanelPopUps.js
  aim/web/ui/src/screens/hub/HubMainScreen/models/HubMainScreenModel.js
  aim/web/ui/src/screens/hub/HubMainScreen/models/TraceList.js
  aim/web/ui/src/storeUtils.js
Labels: enhancement

#482 Hoist context table state to the parent container
  aim/web/ui/src/components/hub/ContextTable/ContextTable.js
  aim/web/ui/src/screens/hub/HubExperimentsDashboardScreen/components/Runs/Runs.js
  aim/web/ui/src/screens/hub/HubMainScreen/HubMainScreen.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/ContextBox/ContextBox.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/ControlsSidebar/components/ControlsSidebarAxesProperties/ControlsSidebarAxesProperties.js
  aim/web/ui/src/screens/hub/HubMainScreen/models/HubMainScreenModel.js
  aim/web/ui/src/ui/components/Table/Table.js
Labels: review needed

#481 Add ability to save explore state/view as bookmark
  CHANGELOG.md
  aim/web/app/__init__.py
  aim/web/app/commits/models.py
  aim/web/app/dashboard_apps/__init__.py
  aim/web/app/dashboard_apps/models.py
  aim/web/app/dashboard_apps/serializers.py
  aim/web/app/dashboard_apps/views.py
  aim/web/app/dashboards/__init__.py
  aim/web/app/dashboards/models.py
  aim/web/app/dashboards/serializers.py
  aim/web/app/dashboards/views.py
  aim/web/app/utils.py
  aim/web/migrations/versions/5ae8371b7481_.py
  aim/web/ui/src/App.js
  aim/web/ui/src/actions/hub/app.js
  aim/web/ui/src/actions/hub/dashboard.js
  aim/web/ui/src/components/global/Header/Header.js
  aim/web/ui/src/constants/classes.js
  aim/web/ui/src/constants/screens.js
  aim/web/ui/src/screens/hub/HubBookmarksScreen/HubBookmarksScreen.js
  aim/web/ui/src/screens/hub/HubBookmarksScreen/HubBookmarksScreen.less
  aim/web/ui/src/screens/hub/HubMainScreen/HubMainScreen.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/ContextBox/ContextBox.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/ControlsSidebar/ControlsSidebar.less
  aim/web/ui/src/screens/hub/HubMainScreen/components/ControlsSidebar/components/ControlsSidebarHighlightMode/ControlsSidebarHighlightMode.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/ControlsSidebar/components/ControlsSidebarZoom/ControlsSidebarZoom.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/Panel/components/PopUp/PanelPopUps.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/SaveAsModal/SaveAsModal.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/SaveAsModal/SaveAsModal.less
  aim/web/ui/src/screens/hub/HubMainScreen/components/SelectForm/components/SidebarMenu/SidebarMenu.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/SelectForm/components/SidebarMenu/SidebarMenu.less
  aim/web/ui/src/screens/hub/HubMainScreen/models/HubMainScreenModel.js
  aim/web/ui/src/storeUtils.js
Labels: enhancement, review needed

#486 Minimize and compress JS bundles size
  aim/web/app/utils.py
  aim/web/app/views.py
  aim/web/ui/package.json
  aim/web/ui/src/App.js
  aim/web/ui/src/components/global/Header/Header.js
Labels: enhancement

#488 Add ability to export table data as CSV
  CHANGELOG.md
  aim/web/ui/package.json
  aim/web/ui/src/components/hub/ContextTable/ContextTable.js
  aim/web/ui/src/components/hub/ContextTable/components/BarExport/BarExport.js
  aim/web/ui/src/components/hub/ContextTable/components/BarExport/BarExport.less
  aim/web/ui/src/screens/hub/HubExperimentsDashboardScreen/components/Runs/Runs.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/ContextBox/ContextBox.js
  aim/web/ui/src/utils/index.js
Labels: review needed

#493 Fix CSV export data selection on explore and dashboard pages
  aim/web/ui/src/components/hub/ContextTable/components/BarExport/BarExport.less
  aim/web/ui/src/screens/hub/HubExperimentsDashboardScreen/components/Runs/Runs.js
  aim/web/ui/src/screens/hub/HubMainScreen/components/ContextBox/ContextBox.js
Labels: review needed

#498 Initialize UI new version app structure
  aim/web/ui_v2/.gitignore
  aim/web/ui_v2/.prettierrc
  aim/web/ui_v2/package.json
  aim/web/ui_v2/public/favicon.png
  aim/web/ui_v2/public/index.html
  aim/web/ui_v2/public/logo.png
  aim/web/ui_v2/public/manifest.json
  aim/web/ui_v2/public/robots.txt
  aim/web/ui_v2/src/App.test.tsx
  aim/web/ui_v2/src/App.tsx
  aim/web/ui_v2/src/assets/logo-white.png
  aim/web/ui_v2/src/components/ErrorBoundary/ErrorBoundary.tsx
  aim/web/ui_v2/src/components/ProjectWrapper/ProjectWrapper.tsx
  aim/web/ui_v2/src/components/SideBar/SideBar.tsx
  aim/web/ui_v2/src/components/SideBar/style.ts
  aim/web/ui_v2/src/components/Theme/Theme.tsx
  aim/web/ui_v2/src/config/config.ts
  aim/web/ui_v2/src/hooks/model/useModel.ts
  aim/web/ui_v2/src/index.tsx
  aim/web/ui_v2/src/pages/Metrics/Metrics.tsx
  aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui_v2/src/pages/Metrics/components/AppBar/AppBar.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx
  aim/web/ui_v2/src/pages/Metrics/components/Grouping/Grouping.tsx
  aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.tsx
  aim/web/ui_v2/src/pages/Runs/Runs.tsx
  aim/web/ui_v2/src/react-app-env.d.ts
  aim/web/ui_v2/src/reportWebVitals.ts
  aim/web/ui_v2/src/routes/routes.tsx
  aim/web/ui_v2/src/services/api/api.ts
  aim/web/ui_v2/src/services/api/metrics/metricsService.ts
  aim/web/ui_v2/src/services/api/projects/projectsService.ts
  aim/web/ui_v2/src/services/models/metrics/metricsCollectionModel.ts
  aim/web/ui_v2/src/services/models/metrics/metricsModel.ts
  aim/web/ui_v2/src/services/models/metrics/seriesModel.ts
  aim/web/ui_v2/src/services/models/model.ts
  aim/web/ui_v2/src/services/models/projects/projectsModel.ts
  aim/web/ui_v2/src/setupTests.ts
  aim/web/ui_v2/src/types/components/ErrorBoundary/ErrorBoundary.d.ts
  aim/web/ui_v2/src/types/components/Theme/Theme.d.ts
  aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui_v2/src/types/pages/runs/Runs.d.ts
  aim/web/ui_v2/src/types/services/models/model.d.ts
  aim/web/ui_v2/src/types/services/models/projects/projectsModel.d.ts
  aim/web/ui_v2/tsconfig.json
Labels: review needed
