Repository aimhubio/aim, pull requests merged in 2021-10, with the labels that each got.

#819 Filter out runs with missing params in HighPlot
  aim/web/ui/src/services/models/params/paramsAppModel.ts
Labels: approved

#820 Fix persistence change functionality
  aim/web/ui/package-lock.json
  aim/web/ui/package.json
  aim/web/ui/src/pages/Metrics/components/ColorPopoverAdvanced/ColorPopoverAdvanced.tsx
  aim/web/ui/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.tsx
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
  aim/web/ui/src/services/models/runs/runsAppModel.ts
  aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts
  aim/web/ui/src/utils/encoder/encoder.ts
Labels: review needed

#822 Add shuffling seed value functionality
  aim/web/ui/src/components/AppBar/AppBar.scss
  aim/web/ui/src/components/AxesScalePopover/AxesScalePopover.scss
  aim/web/ui/src/components/ControlPopover/ControlPopover.scss
  aim/web/ui/src/components/CustomTable/Table.scss
  aim/web/ui/src/components/Theme/Theme.tsx
  aim/web/ui/src/components/ToggleButton/ToggleButton.scss
  aim/web/ui/src/pages/Metrics/Metrics.tsx
  aim/web/ui/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui/src/pages/Metrics/components/ColorPopoverAdvanced/ColorPopoverAdvanced.scss
  aim/web/ui/src/pages/Metrics/components/ColorPopoverAdvanced/ColorPopoverAdvanced.tsx
  aim/web/ui/src/pages/Metrics/components/Grouping/Grouping.tsx
  aim/web/ui/src/pages/Metrics/components/GroupingItem/groupingItemStyle.scss
  aim/web/ui/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.scss
  aim/web/ui/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.tsx
  aim/web/ui/src/pages/Params/Params.tsx
  aim/web/ui/src/pages/Params/ParamsContainer.tsx
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/services/models/params/paramsAppModel.ts
  aim/web/ui/src/styles/abstracts/_variables.scss
  aim/web/ui/src/styles/components/_inputs.scss
  aim/web/ui/src/types/components/GroupingPopover/GroupingPopover.d.ts
  aim/web/ui/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui/src/types/pages/metrics/components/Grouping/Grouping.d.ts
  aim/web/ui/src/types/pages/params/Params.d.ts
Labels: review needed

#825 Tune styles in explore pages
  aim/web/ui/src/components/GroupingPopover/GroupingPopover.scss
  aim/web/ui/src/components/GroupingPopover/GroupingPopover.tsx
  aim/web/ui/src/components/Table/Table.scss
  aim/web/ui/src/components/Table/Table.tsx
  aim/web/ui/src/components/Table/TableSortIcons.tsx
  aim/web/ui/src/components/TagLabel/TagLabel.scss
  aim/web/ui/src/components/TagLabel/TagLabel.tsx
  aim/web/ui/src/components/TooltipContentPopover/TooltipContentPopover.tsx
  aim/web/ui/src/fonts/icomoon/fonts/icomoon.eot
  aim/web/ui/src/fonts/icomoon/fonts/icomoon.svg
  aim/web/ui/src/fonts/icomoon/fonts/icomoon.ttf
  aim/web/ui/src/fonts/icomoon/fonts/icomoon.woff
  aim/web/ui/src/fonts/icomoon/icomoonIcons.scss
  aim/web/ui/src/fonts/icomoon/selection.json
  aim/web/ui/src/pages/Metrics/Metrics.tsx
  aim/web/ui/src/pages/Metrics/MetricsContainer.tsx
  aim/web/ui/src/pages/Metrics/components/GroupingItem/GroupingItem.scss
  aim/web/ui/src/pages/Metrics/components/GroupingItem/GroupingItem.tsx
  aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx
  aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ColumnItem/ColumnItem.tsx
  aim/web/ui/src/pages/Metrics/components/Table/SortPopover/SortPopover.scss
  aim/web/ui/src/pages/Metrics/components/Table/SortPopover/SortPopover.tsx
  aim/web/ui/src/services/models/metrics/metricsAppModel.ts
  aim/web/ui/src/styles/_global.scss
  aim/web/ui/src/styles/abstracts/_variables.scss
  aim/web/ui/src/styles/components/_inputs.scss
  aim/web/ui/src/types/components/Icon/Icon.d.ts
  aim/web/ui/src/types/components/TagLabel/TagLabel.d.ts
  aim/web/ui/src/types/pages/metrics/Metrics.d.ts
  aim/web/ui/src/types/pages/metrics/components/SelectForm/SelectForm.d.ts
Labels: review needed

#932 Format system metrics names in Table component
  aim/web/ui/src/components/ChartPanel/PopoverContent/PopoverContent.tsx
  aim/web/ui/src/components/GroupConfigPopover/GroupConfigPopover.tsx
  aim/web/ui/src/components/SideBar/SideBar.tsx
  aim/web/ui/src/components/SideBar/Sidebar.scss
  aim/web/ui/src/components/Table/Table.tsx
  aim/web/ui/src/config/systemMetrics/systemMetrics.ts
  aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx
  aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ColumnItem/ColumnItem.tsx
  aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.tsx
  aim/web/ui/src/pages/Metrics/components/Table/SortPopover/SortPopover.tsx
  aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
  aim/web/ui/src/pages/RunDetail/RunMetricCard.tsx
  aim/web/ui/src/pages/Runs/components/RunsTableGrid/RunsTableGrid.tsx
  aim/web/ui/src/utils/d3/drawArea.ts
  aim/web/ui/src/utils/d3/drawParallelAxes.ts
Labels: phase / review-needed

#914 Enhance Badge component
  aim/web/ui/package-lock.json
  aim/web/ui/package.json
  aim/web/ui/src/components/GroupingPopover/GroupingPopover.tsx
  aim/web/ui/src/components/SelectTag/SelectTag.tsx
  aim/web/ui/src/components/kit/Badge/Badge.d.ts
  aim/web/ui/src/components/kit/Badge/Badge.scss
  aim/web/ui/src/components/kit/Badge/Badge.tsx
  aim/web/ui/src/pages/Bookmarks/Bookmarks.tsx
  aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
  aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
  aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.tsx
  aim/web/ui/src/styles/_global.scss
  aim/web/ui/src/styles/abstracts/_variables.scss
Labels: phase / review-needed
